name: .NET Core publish

on: [push]

strategy:
  matrix:
    runtime: [win-x64]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Building ${{ matrix.runtime }}
      run: dotnet publish -r ${{ matrix.runtime }} -c Release /p:PublishSingleFile=true
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.runtime }} build
        path: bin/Release/netcoreapp3.1/${{ matrix.runtime }}/publish