name: .NET Core publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [win-x64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Building ${{ matrix.runtime }}
      run: dotnet publish -r ${{ matrix.runtime }} -c Release /p:PublishSingleFile=true /p:CopyOutputSymbolsToPublishDirectory=false /p:VersionSuffix=gh-$GITHUB_SHA
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.runtime }} build
        path: bin/Release/net5.0/${{ matrix.runtime }}/publish